[package]
name = "zs-apc-spdu-ctl"
version = "0.0.3"
authors = ["zseri <zseri.devel@ytrizja.de>"]
edition = "2018"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"

[dependencies]
ctor = "0.1"
dns-lookup = "1.0"
libc = "0.2"
indoc = "1.0"
