[package]
    name = apc-device-ctl

    [package.version]
	major = 0
	minor = 1
	patch = 0
	api = 1
	name = newdoors

[config]
    file = "/etc/apc-device-ctl.conf"

[log]
    file = "/var/log/apc-device-ctl.log"
